package com.doocker.crm.po;

public class Clazz {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazzid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    private Integer clazzid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.clazzname
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    private String clazzname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.courseid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    private Integer courseid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazzid
     *
     * @return the value of clazz.clazzid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public Integer getClazzid() {
        return clazzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazzid
     *
     * @param clazzid the value for clazz.clazzid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public void setClazzid(Integer clazzid) {
        this.clazzid = clazzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.clazzname
     *
     * @return the value of clazz.clazzname
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public String getClazzname() {
        return clazzname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.clazzname
     *
     * @param clazzname the value for clazz.clazzname
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public void setClazzname(String clazzname) {
        this.clazzname = clazzname == null ? null : clazzname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.courseid
     *
     * @return the value of clazz.courseid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.courseid
     *
     * @param courseid the value for clazz.courseid
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }
}