package com.doocker.crm.po;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseid
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    private Integer courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coursename
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.description
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.learntime
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    private Integer learntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.money
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    private Integer money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseid
     *
     * @return the value of course.courseid
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public Integer getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseid
     *
     * @param courseid the value for course.courseid
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public void setCourseid(Integer courseid) {
        this.courseid = courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coursename
     *
     * @return the value of course.coursename
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coursename
     *
     * @param coursename the value for course.coursename
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.description
     *
     * @return the value of course.description
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.description
     *
     * @param description the value for course.description
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.learntime
     *
     * @return the value of course.learntime
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public Integer getLearntime() {
        return learntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.learntime
     *
     * @param learntime the value for course.learntime
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public void setLearntime(Integer learntime) {
        this.learntime = learntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.money
     *
     * @return the value of course.money
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.money
     *
     * @param money the value for course.money
     *
     * @mbggenerated Tue Jul 25 14:48:38 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }
}