package com.doocker.crm.mapper;

import com.doocker.crm.po.Clazz;
import com.doocker.crm.po.ClazzExample;

import java.util.HashMap;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClazzMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int countByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int deleteByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int deleteByPrimaryKey(Integer clazzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    List<Clazz> selectByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    Clazz selectByPrimaryKey(Integer clazzid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int updateByExample(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbggenerated Tue Jul 25 14:57:24 CST 2017
     */
    int updateByPrimaryKey(Clazz record);
    
    //根据班级名称，分页查询
    List<HashMap> selectByPage(@Param("clazzName")String clazzName);
}